/* tslint:disable */
/* eslint-disable */
/**
 * News Network API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeedItem,
  NewsPostRequest,
} from '../models/index';
import {
    FeedItemFromJSON,
    FeedItemToJSON,
    NewsPostRequestFromJSON,
    NewsPostRequestToJSON,
} from '../models/index';

export interface NewsPostOperationRequest {
    newsPostRequest?: NewsPostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get the latest news feed
     */
    async newsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FeedItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/news`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedItemFromJSON));
    }

    /**
     * Get the latest news feed
     */
    async newsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FeedItem>> {
        const response = await this.newsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new item
     */
    async newsPostRaw(requestParameters: NewsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FeedItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/news`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewsPostRequestToJSON(requestParameters.newsPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FeedItemFromJSON));
    }

    /**
     * Create a new item
     */
    async newsPost(requestParameters: NewsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FeedItem>> {
        const response = await this.newsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
